import crypto from 'node:crypto';

const ALGORITHM = 'aes-256-gcm';
// In a real production environment, this MUST come from an external KMS (e.g. AWS KMS).
// For local execution, we derive a static 32-byte master key.
const VAULT_MASTER_KEY = process.env.VAULT_MASTER_KEY
  ? Buffer.from(process.env.VAULT_MASTER_KEY, 'hex')
  : crypto.scryptSync('sentinel-x-local-secure-vault', 'sentinel-salt', 32);

/**
 * Encrypts a plaintext secret using AES-256-GCM.
 * This is the industry standard for Authenticated Encryption.
 */
export function encryptSecret(plainText: string): string {
  if (!plainText) return '';

  // 12 bytes is the standard IV size for GCM
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, VAULT_MASTER_KEY, iv);

  let encrypted = cipher.update(plainText, 'utf8', 'hex');
  encrypted += cipher.final('hex');

  // The auth tag proves the ciphertext wasn't tampered with
  const authTag = cipher.getAuthTag().toString('hex');

  // Format: iv:authTag:encryptedData
  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a cipherText generated by encryptSecret.
 */
export function decryptSecret(cipherText: string): string {
  if (!cipherText) return '';

  const parts = cipherText.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid vault cipherText format');
  }

  const [ivHex, authTagHex, encryptedHex] = parts;

  const iv = Buffer.from(ivHex as string, 'hex');
  const authTag = Buffer.from(authTagHex as string, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, VAULT_MASTER_KEY, iv);

  decipher.setAuthTag(authTag);

  let decrypted = decipher.update(encryptedHex as string, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}
